# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bef5b29838254790e9510f4738b1f0475ba77cf78ec7267fc811121084969701686f92753341d04ab90d5245fff7ccd8a82a7dc5ebd89b1c0007ee64ac68288b

test:
  secret_key_base: a7ca879f2436406e3df5d926fea62b37dff1c50ce7908c17e43a13ff34e7a5d62f5ca7f2b565b4954ff3acdf98031eb45bd779ef4a8d1a5e7a9b04d00f0b5c56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
